### ISSUE TITLE
Drag and drop gestures on iOS work very poorly. Also because of this, drawing is almost impossible

### ISSUE THREAD

**Issue by TitikUniverse** [VickySalunkhe/vs_story_designer#2]
I add a photo, try to drag it, it doesn't work, I try 20 more times. 
Out of 20 attempts to drag a photo, only one is successful. And the same thing happens with the text.
It's the same with drawing.

Zooming in and out of a photo with a scale of two fingers works better, but it doesn't always work.

I tested on a real device iPhone 12 (iOS 16.3), Flutter 3.7.2

If you don't have any ideas how to fix it or you would like to count on my help with the development of the plugin for iOS, contact me titikuniverse@gmail.com . Maybe I can help make this plugin even better.

**Comment by TitikUniverse** [comment]
I also tested on a real Android device and everything works fine

**Comment by TitikUniverse** [comment]
I just noticed that dragging items only works poorly if it's done slowly. If I take an element and immediately start dragging it very sharply and quickly, then it will work. But if I allow a finger delay of at least 50 milliseconds, then it will be impossible to move the object

**Comment by VickySalunkhe** [comment]
Hi @TitikUniverse 
Thank you for bringing this under notice, have fixed the issue you described, and soon will be publishing the changes.
