### ISSUE TITLE
The MANAGE_EXTERNAL_STORAGE permission makes it difficult to publish to Google Play

### ISSUE THREAD

**Issue by TitikUniverse** [VickySalunkhe/vs_story_designer#3]
Issue found: Not a core feature

The feature you identified that is dependent on this permission does not appear to be critical to the core functionality of your app.

Core functionality is defined as the main purpose of the app. Without this core functionality, the app is "broken" or rendered unusable. The core functionality, as well as any core features that comprise this core functionality, must all be prominently documented and promoted in the app's description.

Please update your app so that the feature does not use this permission or ensure that the core functionality is prominently documented and promoted in the app's description and resubmit your app on Play Developer console.

Additionally, follow these steps to bring your app into compliance:

Read more about [Use of All Files Access](https://notifications.google.com/g/p/APdRdFxMpzL-bU9wt5k-xDC1AxbQPi-ohlNED-U69XYKyLOjPqwYNEnEizB88bi6ThfGheYZMYFWt5r7JFsagxga__pNoIdBIf0dulVI9Xntb4-yw3ZoRrp4sZczcVAJaFECHE_O4Go7fmQEkvTVOmi6OKzE-KeOJDer2IFQZnSmdVzJkmMRDbYMY1MN92DIlLsf8GdL6WtEbXDwUv0kMbjU-6zsutfeu6s-d1c9ONy41BnbZXs) Permission
See [Android storage use cases and best practices](https://notifications.google.com/g/p/APdRdFy77g3cBA4k2YYn4cgHlbJbChtUnkgavxVzLxWnFVHCvlTKL-alza_T2AfpX9e8Vw-zBTveJ_P9YM1_fX_9jainrjlyVaqCb9-QngRoUnD-XyfkO2Nt5XPTWvDQ2VAAYnebBrc2OVEOyd7MS2LwyTaqHmbZoA4qrBMvtGZr9klXEypMMYkemeE5fpIs5dC6gVnEIeCIt63Ipoj1E2eUtIdiNqhUFsZtP5c)
About the All Files Access Permission Policy

Files and directory attributes on a user's device are regarded as personal and sensitive user data subject to the [Personal and Sensitive User Data](https://notifications.google.com/g/p/APdRdFzKTbV0QOEn6SlrJ3j4mPH42GEAzKPkoWISmdydJSIiRu8f6a8MfnHcnsZEdakI2pEIdQYpE3Jx-rH2s5QtDgxYJiWtxwcr2SPBJUli8U5NBRHEM-pPteYM1yHZG2GyhI52TKaO4Q1w16Py2ovYFQ1m-TXtF16rddTnj7V85WANbBlaNP1NxdEA1Vm7ZHbhzaDnvAtU9APhgeLuN-vZi-zej0vFKKRMFeCOlHw_YdxFhZ88) policy and the following requirements:
Apps should only request access to device storage which is critical for the app to function, and may not request access to device storage on behalf of any third-party for any purpose that is unrelated to critical user-facing app functionality.
Android devices running Android "R" (Android 11) or later, will require the [MANAGE_EXTERNAL_STORAGE](https://notifications.google.com/g/p/APdRdFyvNyQVBjy_EEbJPi76Zvbks5u6W8x_ODsBrnc8SWaVHWbcwpvpQ_bq5MC8coK7-LwHuLJQvDcETVbDk0EWK7QQ8_dM7xMBx4lPDNYSi2OxOK38EaYC5YNKM_Nzn059jenejedMiDFWvDb4r2bWwFiN_M_t8eZaZFciPBVLa0640CegMvB8eZ-4akNQawi5LtpRIToex0wS93n6fqiUJ0rY8oa5ROTkMpifIHT5KfwhLGF0v-TmRESSslrRp0AaYSbCbXm1ThA) permission in order to manage access in shared storage. All apps that target R or later and request broad access to shared storage ("All files access") must successfully pass an appropriate access review prior to publishing. Apps allowed to use this permission must clearly prompt users to enable "All files access" for their app under "Special app access" settings. For more information on the R requirements, please see this [help article](https://notifications.google.com/g/p/APdRdFxMpzL-bU9wt5k-xDC1AxbQPi-ohlNED-U69XYKyLOjPqwYNEnEizB88bi6ThfGheYZMYFWt5r7JFsagxga__pNoIdBIf0dulVI9Xntb4-yw3ZoRrp4sZczcVAJaFECHE_O4Go7fmQEkvTVOmi6OKzE-KeOJDer2IFQZnSmdVzJkmMRDbYMY1MN92DIlLsf8GdL6WtEbXDwUv0kMbjU-6zsutfeu6s-d1c9ONy41BnbZXs).

Issue found: Need to use Media Store API or No Access to Files

You have requested access to All Files Access permission but it appears that your app's core feature requires access to only Media Files or does not need access to any Files. In case your app needs access to Media Files, with the [MediaStore API](https://notifications.google.com/g/p/APdRdFxHvrQBx_nChGdYKIWti7_fmDCTqJ-8GcD9nS9_XERUVc8zzuP4IQ5Qm-v5U5oqhhPat4n5rYH4xhOliaw3ngW7Odoe70OnA3qpaxMRFtNmyF8h64h7HHY3BrN1k2hH9po3S8XPUZ3QsrIUD95bfqPLqX-Dljx4Ht6jtnrhJvneUAY-DcH7Z6oPGX_rZo2jBDaTEUdrW1fIlobWF53Hhn4r2tRnHkFfSb2WoiQ), apps can contribute and access media that's available on an external storage volume without the need for the access all files permission.

Please update your app so that the feature uses Media Store APIs and remove All Files Access (MANAGE_EXTERNAL_STORAGE) permission.

Additionally, follow these steps to bring your app into compliance:

Read more about [Use of All Files Access](https://notifications.google.com/g/p/APdRdFxMpzL-bU9wt5k-xDC1AxbQPi-ohlNED-U69XYKyLOjPqwYNEnEizB88bi6ThfGheYZMYFWt5r7JFsagxga__pNoIdBIf0dulVI9Xntb4-yw3ZoRrp4sZczcVAJaFECHE_O4Go7fmQEkvTVOmi6OKzE-KeOJDer2IFQZnSmdVzJkmMRDbYMY1MN92DIlLsf8GdL6WtEbXDwUv0kMbjU-6zsutfeu6s-d1c9ONy41BnbZXs) Permission
See [Android storage use cases and best practices](https://notifications.google.com/g/p/APdRdFy77g3cBA4k2YYn4cgHlbJbChtUnkgavxVzLxWnFVHCvlTKL-alza_T2AfpX9e8Vw-zBTveJ_P9YM1_fX_9jainrjlyVaqCb9-QngRoUnD-XyfkO2Nt5XPTWvDQ2VAAYnebBrc2OVEOyd7MS2LwyTaqHmbZoA4qrBMvtGZr9klXEypMMYkemeE5fpIs5dC6gVnEIeCIt63Ipoj1E2eUtIdiNqhUFsZtP5c) and how to [access media files from shared storage](https://notifications.google.com/g/p/APdRdFxHvrQBx_nChGdYKIWti7_fmDCTqJ-8GcD9nS9_XERUVc8zzuP4IQ5Qm-v5U5oqhhPat4n5rYH4xhOliaw3ngW7Odoe70OnA3qpaxMRFtNmyF8h64h7HHY3BrN1k2hH9po3S8XPUZ3QsrIUD95bfqPLqX-Dljx4Ht6jtnrhJvneUAY-DcH7Z6oPGX_rZo2jBDaTEUdrW1fIlobWF53Hhn4r2tRnHkFfSb2WoiQ)
About the All Files Access Permission Policy

Files and directory attributes on a user's device are regarded as personal and sensitive user data subject to the [Personal and Sensitive User Data](https://notifications.google.com/g/p/APdRdFzKTbV0QOEn6SlrJ3j4mPH42GEAzKPkoWISmdydJSIiRu8f6a8MfnHcnsZEdakI2pEIdQYpE3Jx-rH2s5QtDgxYJiWtxwcr2SPBJUli8U5NBRHEM-pPteYM1yHZG2GyhI52TKaO4Q1w16Py2ovYFQ1m-TXtF16rddTnj7V85WANbBlaNP1NxdEA1Vm7ZHbhzaDnvAtU9APhgeLuN-vZi-zej0vFKKRMFeCOlHw_YdxFhZ88) policy and the following requirements:
Apps should only request access to device storage which is critical for the app to function, and may not request access to device storage on behalf of any third-party for any purpose that is unrelated to critical user-facing app functionality.
Android devices running Android "R" (Android 11) or later, will require the [MANAGE_EXTERNAL_STORAGE](https://notifications.google.com/g/p/APdRdFyvNyQVBjy_EEbJPi76Zvbks5u6W8x_ODsBrnc8SWaVHWbcwpvpQ_bq5MC8coK7-LwHuLJQvDcETVbDk0EWK7QQ8_dM7xMBx4lPDNYSi2OxOK38EaYC5YNKM_Nzn059jenejedMiDFWvDb4r2bWwFiN_M_t8eZaZFciPBVLa0640CegMvB8eZ-4akNQawi5LtpRIToex0wS93n6fqiUJ0rY8oa5ROTkMpifIHT5KfwhLGF0v-TmRESSslrRp0AaYSbCbXm1ThA) permission in order to manage access in shared storage. All apps that target R or later and request broad access to shared storage ("All files access") must successfully pass an appropriate access review prior to publishing. Apps allowed to use this permission must clearly prompt users to enable "All files access" for their app under "Special app access" settings. For more information on the R requirements, please see this [help article](https://notifications.google.com/g/p/APdRdFxMpzL-bU9wt5k-xDC1AxbQPi-ohlNED-U69XYKyLOjPqwYNEnEizB88bi6ThfGheYZMYFWt5r7JFsagxga__pNoIdBIf0dulVI9Xntb4-yw3ZoRrp4sZczcVAJaFECHE_O4Go7fmQEkvTVOmi6OKzE-KeOJDer2IFQZnSmdVzJkmMRDbYMY1MN92DIlLsf8GdL6WtEbXDwUv0kMbjU-6zsutfeu6s-d1c9ONy41BnbZXs).

**Comment by VickySalunkhe** [comment]
You can remove that permission from your manifest file.
and use media queries instead.

**Remove**
`<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />`

**Use** 
```
     <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
```
